modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="millenaire"
version="${file.jarVersion}"
displayName="Millenaire Mod"
description="Adds historical civilizations to Minecraft"
authors="Koriak"
credits="Original Millenaire team"
logoFile="assets/millenaire/textures/logo.png"

[[dependencies.millenaire]]
modId="forge"
versionRange="[47,)"
mandatory=true

[[dependencies.millenaire]]
modId="minecraft"
versionRange="[1.20.1]"
mandatory=true
