modLoader="javafml"
loaderVersion="[47,)" 
license="All rights reserved"
issueTrackerURL="https://github.com/yourusername/Mod-millenaire/issues"

[[mods]]
modId="millenaire" 
version="1.0.0"
displayName="Millénaire Mod"
authors="YourName"
description='''
Un mod ajoutant des civilisations médiévales dynamiques à Minecraft
'''
logoFile="millenaire_logo.png"

[[dependencies.millenaire]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.millenaire]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
